# Change these first
owner: mioscape # Your GitHub organization or username, where this repository lives
repo: mioscape-uptime-status # The name of this repository

sites:
  - name: Mioscape Profile
    url: https://mioscape.cf/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
  - name: Mioscape Blog
    url: https://blog.mioscape.cf/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
  - name: Mioscape Index
    url: https://index.mioscape.cf/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
  - name: Mioscape VPN Subscription
    url: https://subscription.mioscape.cf/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
  - name: Mioscape VPN Server
    url: https://vpn.mioscape.cf/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
  - name: Mioscape Server Status
    url: https://status.mioscape.cf/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mioscape.cf
  # baseUrl: /your-repo-name
  favicon: https://avatars.githubusercontent.com/u/43681888?v=4
  logoUrl: https://avatars.githubusercontent.com/u/43681888?v=4
  name: mioscape.cf - Server Status
  introTitle: "Welcome to our **mioscape.cf** server status page."
  introMessage: You can get updates on how our systems are doing. If there are interruptions to service, we will post a note here.
  theme: dark
  navbar:
    - title: Profile
      href: https://mioscape.cf/
    - title: Blog
      href: https://blog.mioscape.cf/
    - title: Index
      href: https://index.mioscape.cf/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Telegram
      href: https://t.me/mioscape

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
