# Change these first
owner: mioscape # Your GitHub organization or username, where this repository lives
repo: mioscape-uptime-status # The name of this repository

sites:
  - name: Mioscape Homepage
    url: https://ihya.dev/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
  - name: Mioscape Blog
    url: https://blog.ihya.dev/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
  - name: Mioscape VPN Subscription
    url: https://subscription.ihya.dev/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
  - name: Mioscape Server Status
    url: https://status.ihya.dev/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
  - name: Mioscape ShitBin
    url: https://shitbin.ihya.dev/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
  - name: Mioscape Music
    url: https://music.ihya.dev/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500
  - name: Mioscape Drive
    url: https://drive.ihya.dev/
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 500

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ihya.dev
  # baseUrl: /your-repo-name
  favicon: https://avatars.githubusercontent.com/u/43681888?v=4
  logoUrl: https://avatars.githubusercontent.com/u/43681888?v=4
  name: ihya.dev - Server Status
  introTitle: "Welcome to our **ihya.dev** server status page."
  introMessage: You can get updates on how our systems are doing. If there are interruptions to service, we will post a note here.
  theme: night
  navbar:
    - title: Homepage
      href: https://ihya.dev/
    - title: Blog
      href: https://blog.ihya.dev/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Telegram
      href: https://t.me/mioscape
      
i18n:
  footer: This page is [open source]($REPO), powered by [Mioscape](https://ihya.dev)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
